### ISSUE TITLE
Issue with the execution of the program

### ISSUE THREAD

**Issue by go4mbbs** [ErikHansenGit/EHL#1]
Seems very promising program but unable to get it to work. As I click on run on any of the study, an error is received like the following on MATLAB 2022b:

```
Unable to resolve the name 'autorun.alg.Sim_ID'.

Error in EHL_01_setup_Study_A_gen (line 16)
alg.Sim_ID = autorun.alg.Sim_ID{autorun.sim.it};
```

**Comment by go4mbbs** [comment]
https://user-images.githubusercontent.com/67873193/233595124-f0ee9a4d-687b-4e1e-b197-2a2649bf4485.mp4
 I have also attached a screencast of the issue as it happens. Please comment. I will really appreciate it. Thanks a lot.

**Comment by ErikHansenGit** [comment]
Hello and thank you for your question.

The easy fix would be to run the script `EHL_00_run_Study_A_gen.m` instead of `EHL_01_setup_Study_A_gen.m`.

The reason is that the `EHL_00_run_Study_A_gen.m` script creates the `autorun` variable and then calls the `EHL_01_setup_Study_A_gen.m` and `EHL_02_mainprocess.m` scripts. The first one reads in the `autorun` variable and sets all remaining parameters while the second one executes the simulation. This is to automatize the consecutive execution of several simulations that only vary by a couple of parameters.

If you want to run only a single simulation, you can directly specify any of the parameters within `autorun` in the beginning of the `01` script, run the `01` script and then run the `EHL_02_mainprocess.m` script on your own.
Alternatively you can disable the `for` loop the `EHL_00_run_Study_A_gen.m` script and set `autorun.sim.it` to the counter of the simulation that you want to run.

Best regards

**Comment by go4mbbs** [comment]
Perfect. Thank you very much!

**Comment by go4mbbs** [comment]
Issue resolved
